call %~dp0..\Scriptsctivate.bat
pip install alabaster
pip install appdirs
pip install attrdict
pip install attrs
pip install babel
pip install backcall
pip install cachey
pip install cuda-slic
pip install docutils
pip install freetype-py
pip install humanize
pip install imagesize
pip install importlib-metadata
pip install iniconfig
pip install ipykernel
pip install ipython
pip install ipython-genutils
pip install jedi
pip install jupyter-client
pip install jupyter-core
pip install kornia
pip install mako
pip install more-itertools
pip install morphsnakes
pip install mrcfile
pip install napari
pip install napari-plugin-engine
pip install napari-svg
pip install nibabel
pip install nose
pip install numpydoc
pip install parse
pip install parso
pip install pexpect
pip install pickleshare
pip install pluggy
pip install prompt-toolkit
pip install ptyprocess
pip install py
pip install pycuda
pip install pydantic
pip install pygments
pip install pyopengl
pip install pytest
pip install python-deprecated
pip install pytools
pip install pyzmq
pip install qtconsole
pip install simpleitk
pip install snowballstemmer
pip install sphinx
pip install sphinxcontrib-applehelp
pip install sphinxcontrib-devhelp
pip install sphinxcontrib-htmlhelp
pip install sphinxcontrib-jsmath
pip install sphinxcontrib-qthelp
pip install sphinxcontrib-serializinghtml
pip install tensorly
pip install toml
pip install torchio
pip install tqdm
pip install traitlets
pip install vispy
pip install wcwidth
pip install wget
pip install wrapt
pip install zipp
